// Every icon of the site, derived from ONE file: brand/mark.svg (the mark alone, on nothing). To change the
// site's icon, change that file (or the table below) and run `npm run icons`; nothing else is drawn by hand.
//
//   brand/favicon.svg            browser tabs: the mark on a rounded tile, so it reads on light and dark tabs
//   brand/favicon-32.png         the same, for browsers without SVG favicons
//   favicon.ico                  the same at 16, 32 and 48 px, at the site's root, where some browsers and
//                                places (bookmarks, history, search results) look whatever the page declares
//   brand/apple-touch-icon.png   the iOS home-screen icon (iOS reads no manifest for it): a full-bleed
//                                square, the system rounds its corners
//   brand/icon-192.png, -512     the installed app's icons (the web app manifest)
//   brand/icon-maskable-512.png  Android's: the mark inside the safe zone, the launcher crops it to its shape
//   brand/site.webmanifest       the web app manifest naming them
//
// The app itself shows brand/mark.svg as it is (the top bar, the landing page, Brighter Fashion's pictures).
// PNGs are drawn by headless Chrome from the composed SVG, so they match the mark exactly.
import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import puppeteer from 'puppeteer-core';
import { CHROME } from './chrome.ts';

const WEBAPP = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const BRAND = path.join(WEBAPP, 'brand');

// ---- the look: change these (or brand/mark.svg), then run npm run icons -------------------------------
const NAME = 'Brighter Atlas';
const DESCRIPTION = 'Fan-made tools for Brighter Shores: Brighter Fashion, Brighter Maps and Brighter Data.';
const THEME = '#12151b';                                   // the page's own colour (index.html theme-color)
const TILE = '#161a22';                                    // the favicon's tile
const GLOW = { inner: '#1e2738', outer: '#0f1217' };       // the app icons' background, a soft glow behind the mark
/** Where the mark's visual centre sits in its 32 x 32 box (its spires rise higher than its feet sink). */
const MARK_CENTRE = { x: 16, y: 15.9 };
type Background = 'tile' | 'glow';
/** Each derived look: its background, and the mark's size in it (1 = the mark's own 32 x 32 box). */
const LOOKS: Record<string, { background: Background; scale: number }> = {
  favicon: { background: 'tile', scale: 0.85 },
  app: { background: 'glow', scale: 0.9 },                 // a little margin all round
  maskable: { background: 'glow', scale: 0.62 },           // inside Android's safe zone (a circle of 80%)
};
// --------------------------------------------------------------------------------------------------------

const mark = readFileSync(path.join(BRAND, 'mark.svg'), 'utf8')
  .replace(/^[\s\S]*?<svg[^>]*>/, '').replace(/<\/svg>\s*$/, '').replace(/<!--[\s\S]*?-->/g, '').trim();

/** A look as an SVG document: its background, and the mark centred on it at its size. */
function compose(look: keyof typeof LOOKS): string {
  const { background, scale } = LOOKS[look];
  const tx = MARK_CENTRE.x * (1 - scale), ty = 16 - MARK_CENTRE.y * scale;
  const ground = background === 'tile'
    ? `<rect width="32" height="32" rx="7" fill="${TILE}"/>`
    : `<defs><radialGradient id="glow" cx="50%" cy="42%" r="75%"><stop offset="0" stop-color="${GLOW.inner}"/>`
      + `<stop offset="1" stop-color="${GLOW.outer}"/></radialGradient></defs><rect width="32" height="32" fill="url(#glow)"/>`;
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32">\n`
    + `<!-- generated by tools/icons.ts from brand/mark.svg (the "${look}" look): do not edit -->\n`
    + `${ground}\n<g transform="translate(${tx.toFixed(3)} ${ty.toFixed(3)}) scale(${scale})">\n${mark}\n</g>\n</svg>\n`;
}

/** An .ico holding PNG images (every browser since IE 9 reads PNG entries). */
function ico(images: { size: number; png: Buffer }[]): Buffer {
  const head = Buffer.alloc(6 + 16 * images.length);
  head.writeUInt16LE(0, 0); head.writeUInt16LE(1, 2); head.writeUInt16LE(images.length, 4);
  let offset = head.length;
  images.forEach(({ size, png }, i) => {
    const e = 6 + 16 * i;
    head.writeUInt8(size % 256, e); head.writeUInt8(size % 256, e + 1);   // (256 is written as 0)
    head.writeUInt16LE(1, e + 4); head.writeUInt16LE(32, e + 6);
    head.writeUInt32LE(png.length, e + 8); head.writeUInt32LE(offset, e + 12);
    offset += png.length;
  });
  return Buffer.concat([head, ...images.map((x) => x.png)]);
}

const write = (rel: string, data: string | Buffer, what: string) => {
  writeFileSync(path.join(WEBAPP, rel), data);
  console.log(`${rel}  ${what}`);
};

if (!CHROME) throw new Error('no Chrome found (set CHROME)');
const browser = await puppeteer.launch({ executablePath: CHROME, headless: true, args: ['--no-sandbox'] });
try {
  const page = await browser.newPage();
  const draw = async (look: keyof typeof LOOKS, size: number): Promise<Buffer> => {
    await page.setViewport({ width: size, height: size, deviceScaleFactor: 1 });
    const src = `data:image/svg+xml;base64,${Buffer.from(compose(look)).toString('base64')}`;
    await page.setContent(`<html><body style="margin:0;background:transparent"><img style="display:block;width:${size}px;height:${size}px" src="${src}"></body></html>`);
    await page.waitForFunction(() => (document.querySelector('img') as any).complete);
    return Buffer.from(await page.screenshot({ omitBackground: true, clip: { x: 0, y: 0, width: size, height: size } }));
  };

  write('brand/favicon.svg', compose('favicon'), 'favicon');
  write('brand/favicon-32.png', await draw('favicon', 32), 'favicon, 32 px');
  const sizes = [16, 32, 48], images = [];
  for (const size of sizes) images.push({ size, png: await draw('favicon', size) });
  write('favicon.ico', ico(images), `favicon, ${sizes.join(', ')} px`);
  write('brand/apple-touch-icon.png', await draw('app', 180), 'app, 180 px (iOS home screen)');
  write('brand/icon-192.png', await draw('app', 192), 'app, 192 px');
  write('brand/icon-512.png', await draw('app', 512), 'app, 512 px');
  write('brand/icon-maskable-512.png', await draw('maskable', 512), 'maskable, 512 px');
  write('brand/site.webmanifest', JSON.stringify({
    name: NAME, short_name: NAME, description: DESCRIPTION, start_url: '/', scope: '/', display: 'standalone',
    background_color: THEME, theme_color: THEME,
    icons: [
      { src: '/brand/icon-192.png', sizes: '192x192', type: 'image/png', purpose: 'any' },
      { src: '/brand/icon-512.png', sizes: '512x512', type: 'image/png', purpose: 'any' },
      { src: '/brand/icon-maskable-512.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' },
    ],
  }, null, 2) + '\n', 'the web app manifest');
} finally {
  await browser.close();
}
